name: LigeMCItems
version: '1.1'
main: pl.ligemc.items.LigeMCItems
api-version: '1.21'
commands:
  ligemcitems:
    description: Główna komenda LigeMCItems
    permission: ligemcitems.admin
permissions:
  ligemcitems.admin:
    default: op
